/**
 * SDK-free tool catalog — the {name, summary} projection of the MCP `TOOL_DEFS`
 * registry, kept in a module that carries NO `@modelcontextprotocol/sdk` import so
 * the zero-runtime-dependency CLI (`dist/cli.js`) can enumerate the advertised tool
 * set without dragging the SDK into the CLI bundle (mcp-server.ts:15-18).
 *
 * Source of truth: this list mirrors `TOOL_DEFS` (name + description) EXACTLY, in
 * registry order. `tests/manifest-tools.test.ts` pins the two together, so a tool
 * added/removed/renamed in `TOOL_DEFS` without updating this catalog fails CI —
 * the same drift-guard idiom the order-sensitive tool-name mirrors already use.
 *
 * Consumed by `th manifest tools` (src/commands/manifest.ts) for runtime tool
 * discovery: an agent (or operator) shelling the CLI can list the live tool set
 * instead of relying on a hard-coded list.
 */

export interface ToolCatalogEntry {
  /** The advertised MCP tool name (e.g. `th_state_get`). */
  name: string;
  /** One-block summary — the same text as the tool's MCP `description`. */
  summary: string;
}

/** The {name, summary} projection of TOOL_DEFS, in registry order (SDK-free). */
export const TOOL_CATALOG: readonly ToolCatalogEntry[] = [
  { name: "th_state_get", summary: "Read state.json, or a single value at a dotted path (e.g. `tier`, `slices.0.status`). Read-only." },
  { name: "th_state_set", summary: "Patch a single dotted key in state.json. `value` is JSON-parsed when possible, else stored as a string. Refuses gate-owned fields (implementation_allowed, tier, current_stage, write_gate, blast_radius_flags, and the gate-defining config fields delivery_mode, has_ui, interview_required, interview_cutoff) over MCP — those are changed only through the human-driven CLI flow (`th init` flags or `th state set --emergency`), never an agent tool — plus unknown top-level fields, unsafe key segments, the managed drift/debate counters, and any write that would make state invalid." },
  { name: "th_tier_record", summary: "Record (classify or re-classify) the run's tier. Calls validateTierTransition: refuses t0_blast_radius_veto (T0 with blast-radius flags), tier_locked_after_unlock (once implementation_allowed===true), and tier_downgrade_human_only (a downward re-tier over MCP — a review-dodge vector). Set-from-unclassified and upgrades are allowed. Writes via the locked+ledgered setter (source=th_tier_record)." },
  { name: "th_stage_advance", summary: "Advance to the next APPLICABLE engaged stage for the run (UX/UI stages are skipped when has_ui===false — #13). Calls canAdvanceStage (the full mechanical ladder: blocking drift, revise caps, failing verify, artifact drift, tier set, brownfield repo-map, decision obligations, open debates, the current stage's governing artifact, coverage at implementation-planning, all slices settled at implementation). Refuses with the first failing rung's stable error, or no_next_stage at the terminal stage. Writes current_stage via the locked+ledgered setter (source=th_stage_advance)." },
  { name: "th_implementation_unlock", summary: "Set implementation_allowed. allowed:true requires the FULL canUnlockImplementation ladder (canAdvanceStage's complete ladder + tail: coverage passes AND current_stage ≥ implementation-planning) and refuses with the first failing rung's stable error. allowed:false (re-lock/tighten) is always permitted. Writes via the locked+ledgered setter (source=th_implementation_unlock)." },
  { name: "th_write_gate_set", summary: "Set the PreToolUse write-gate level. TIGHTEN-ONLY over MCP: rank off < ask < deny < strict; any change to a strictly LOWER rank is refused (would_loosen_write_gate). An absent write_gate is treated as the default (ask). Writes via the locked+ledgered setter (source=th_write_gate_set)." },
  { name: "th_blast_radius_record", summary: "Add or remove a §5 blast-radius flag (idempotent merge). present:true adds the flag, present:false removes it. Refuses t0_blast_radius_veto when the current tier is T0 and the result would carry any flag (re-tier above T0 first). Writes the merged, canonically-ordered blast_radius_flags via the locked+ledgered setter (source=th_blast_radius_record)." },
  { name: "th_drift_add", summary: "Append a §10 drift entry. `layer` is required: `requirement` is BLOCKING (increments the open-blocking counter the stop-gate reads); `derived` auto-applies. Optional ref/discovery/action/escalation/source mirror the CLI flags." },
  { name: "th_drift_list", summary: "List recorded §10 drift entries plus the open-blocking count the stop-gate reads. Read-only." },
  { name: "th_drift_resolve", summary: "Resolve an open drift entry by id; decrements the open-blocking counter when it was a requirement-layer (blocking) entry. A requirement-layer (blocking) resolution REQUIRES `target` — a repo-relative source path that resolves in source — and records a BSC-4 terminal-transition receipt the completion gate re-validates. Errors if the id is unknown, already resolved, or (requirement-layer) the target is missing or does not resolve in source. Serialized under the state lock." },
  { name: "th_build_next_wave", summary: "Live wave oracle: the slices dispatchable IN PARALLEL right now (pending, deps done, components free of in-progress slices and live leases). Reports held slices with reasons and flags dependency cycles / dangling refs / stalls. Read-only." },
  { name: "th_build_claim", summary: "Take a live component lease on a slice before spawning its Builder. Refuses (error) if any of the slice's components are already leased to a different slice (collision guard for parallel Builders). Serialized under the state lock." },
  { name: "th_build_release", summary: "Release a slice's component lease after it finishes or blocks." },
  { name: "th_build_dispatch", summary: "Single-payload parallel-dispatch oracle (REQ-PCO-001): the FULL spawn set for the current live wave in one payload — each dispatchable slice enriched with a {model, effort} recommendation from the §2 routing table — so every wave Builder can be launched in one message. Carries dependency-graph/stall warnings. Read-only (the Orchestrator still claims + sets in-progress before spawning)." },
  { name: "th_build_plan", summary: "Schedule the slices into conflict-free build waves (slices sharing a component serialize across waves). By default only unfinished slices are scheduled; includeDone schedules all. advise adds a parallelism-optimizer advisory (REQ-PCO-030). Read-only." },
  { name: "th_route", summary: "Advisory model+effort routing (§2): recommend {model, effort} for an agent spawn from the agent, its mode, the tier, and the blast-radius flags (sourced from state). Read-only: it COMPUTES the recommendation; the Orchestrator still applies the override at spawn." },
  { name: "th_coverage_check", summary: "Hard coverage gate: verify every (MVP) REQ-ID maps to ≥1 slice and ≥1 test. Error (gap) lists each uncovered REQ-ID. Optional reqs/plan/tests/scope paths mirror the CLI flags (defaults: docs/01-requirements.md, docs/09-implementation-plan.md, tests, docs/02-scope.md). Read-only." },
  { name: "th_coverage_report", summary: "Full planned/implemented/tested traceability breakdown for every checked REQ-ID (structured payload). Optional reqs/plan/tests/scope/code path overrides mirror the CLI flags. COMPACT by default — the per-REQ table is collapsed to a headline in the text block (the full breakdown stays in structuredContent); pass `verbose:true` for the full human table. Read-only." },
  { name: "th_next", summary: "Next-action oracle: the single highest-priority MECHANICAL obligation the run owes next (blocking drift, revise caps, failing suite, artifact drift, tier, stage obligations, build waves, …). Reports a mechanical obligation; it never chooses strategy. Read-only." },
  { name: "th_delegate_plan", summary: "Context-preservation oracle: recommend whether a task should be DELEGATED to a child agent or KEPT in the main context, from mechanical signals (intent, expected file reads, source writes, noisy output). Returns the recommendation, reasons, a suggested agent, and whether a handoff/capsule is needed. Advisory: it COMPUTES; the Orchestrator decides. Read-only." },
  { name: "th_delegate_pack", summary: "Assemble a BOUNDED child-agent handoff: the delegated-agent envelope (agent/task/intent/slice/allowed-scope/required-behavior) plus the required Delegation Capsule format. With a slice it reuses `th context pack` for artifact Summary blocks + component-overlap framing. Read-only." },
  { name: "th_delegate_check", summary: "Validate a returned Delegation Capsule: confirm every required section heading is present (presence only — content is not judged). Pass the capsule inline as `text`, or a `path` to a capsule file within the project root. Error lists the missing sections. Read-only." },
  { name: "th_repo_map", summary: "Scan the governed project and build the dual repo-map artifacts (.twinharness/repo-map.json + docs/00-repo-map.md). WRITES both artifacts by default (D-CONTRACTS-001), OVERWRITING any prior repo-map.json and docs/00-repo-map.md. This overwrite is idempotent regeneration of GENERATED_ARTIFACTS — derived content, not authored data — so it is NOT flagged destructive (destructiveHint stays false); re-running reproduces equivalent output rather than losing work. Pass write:false for a dry/preview run that returns the compact summary in memory only — nothing written." },
  { name: "th_repo_relevant", summary: "Read the persisted repo-map and return the files most relevant to a given selector (slice, REQ-ID, file, or free-text query). Read-only. Run th_repo_map first to build/refresh the map." },
  { name: "th_repo_impact", summary: "Read the persisted repo-map and return the blast-radius impact of changing a file or component. Read-only. Run th_repo_map first to build/refresh the map." },
  { name: "th_context_pack", summary: "Assemble the §9 handoff bundle: Summary blocks of every approved artifact, plus (when slice is given) the slice record, its components, and overlap with other slices. Read-only." },
  { name: "th_build_sub_claim", summary: "Open a sub-lease on a SUBSET of a parent slice's components for a scoped sub-Builder. The parent slice must be in-progress. Components must be a non-empty subset of the parent's declared components and disjoint from any live sibling sub-lease." },
  { name: "th_build_sub_release", summary: "Release a sub-lease after the sub-Builder finishes or blocks. Verifies the id names an active sub-lease." },
  { name: "th_repo_check", summary: "Check whether the persisted repo-map.json is stale (files added/removed/modified since the last `th repo map` run). Exit 0 = fresh; exit 4 = stale; exit 5 = no map; exit 1 = parse failure. Read-only; same behavior as `th repo check`." },
  { name: "th_decision_detect", summary: "Surface advisory DecisionCandidate[] from four deterministic on-disk sources (ADRs, drift-log, scope-change signals, state.json blast-radius flags). Read-only; exit 0 always; never writes any state. Same behavior as `th decision detect`." },
  { name: "th_decision_add", summary: "Record one `proposed` decision: mint the next id, set the proposer/proposedAt audit trail. `title` and `rationale` are required. `links` is a comma-separated string (split/trim/drop-empties). Never auto-approves. Same behavior as `th decision add`." },
  { name: "th_decision_check", summary: "Fail (exit 6) when any unapproved decision gates the current stage; pass (exit 0) when all gating decisions are approved or none exist. Uses the single gatingObligations predicate (RULE-007). Same behavior as `th decision check`." },
  { name: "th_decision_list", summary: "Return the reduced decision set, sorted by numeric id suffix. Exit 0 always. Audit fields appear only when applicable to the status. Same behavior as `th decision list`." },
  { name: "th_artifact_register", summary: "Content-hash a file or directory (project-root-relative) and upsert it into approved_artifacts at the given version (re-registering replaces the entry). Rejects absolute paths and `..`/outside-root escapes; surfaces artifact_too_large when the hash byte-budget is exceeded. Serialized under the state lock." },
  { name: "th_artifact_list", summary: "List every recorded approved artifact ({file, version, hash}). Read-only." },
  { name: "th_artifact_claim", summary: "Take a section lease (<file>#<section>) for a holder before editing that section. Refuses (error) if the exact section is already actively leased to a DIFFERENT holder (collision guard); a re-claim by the same holder is idempotent. Serialized under the state lock." },
  { name: "th_artifact_release", summary: "Release a section lease (<file>#<section>) held by a holder." },
  { name: "th_artifact_leases", summary: "List the active section leases ({section, holder}). Read-only." },
  { name: "th_collab_init", summary: "Report the resolved collab directory for a stage (path construction only — dirs are created on the first fragment write). Read-only." },
  { name: "th_collab_fragment", summary: "Drop a fragment file into <stage>/<round>, creating the round dir on demand. Refuses to overwrite an existing fragment unless force is set (collision guard for parallel writers)." },
  { name: "th_collab_list", summary: "List fragment descriptors for a stage (optionally one round) in deterministic sorted order. Read-only." },
  { name: "th_collab_merge", summary: "Reconcile a round: concatenate its fragments in deterministic order (idempotent). Rejects (error) any round containing a fragment without a REQ-ID anchor (traceability §17). Read-only." },
  { name: "th_debate_add", summary: "Log a proposed (BLOCKING) debate over competing producer positions; increments debate_open_blocking so the stop-gate refuses completion until it is resolved. Serialized under the state lock." },
  { name: "th_debate_list", summary: "List debate entries (collapsed to the latest per id, sorted) plus the open-blocking count. Read-only." },
  { name: "th_debate_resolve", summary: "Mark a debate resolved and decrement debate_open_blocking. Errors if the id is unknown or already resolved. Serialized under the state lock." },
  { name: "th_verify_add", summary: "Append a project verify command (e.g. \"npm test\") to verify.json. Commands are operator-authored and executed by th_verify_run." },
  { name: "th_verify_list", summary: "List the configured verify commands. Read-only." },
  { name: "th_verify_clear", summary: "Remove all configured verify commands." },
  { name: "th_verify_run", summary: "Execute every configured verify command in the project root and record the report — the one command that runs project tests. Commands run OUTSIDE the state lock; only the report write is persisted (AC-B11). ASYNC: spawns real OS processes (dispatched via runAsync; `run` is the sync-contract guard)." },
  { name: "th_stage_current", summary: "The stage contract for state.current_stage (or a plain note for a pre-pipeline stage). Read-only." },
  { name: "th_stage_describe", summary: "Describe one pipeline stage's contract (produces / critic mode / human gate / tiers). Read-only." },
  { name: "th_stage_list", summary: "List every pipeline stage with its tiers, human-gate flag, and produced artifact. Read-only." },
  { name: "th_doctor", summary: "Run-health audit: a structured report of artifact drift, slice progress, revise escalations, coverage, and gate posture. Optional strict raises advisories to failures. COMPACT by default — the text block is a headline (full report in structuredContent); pass `verbose:true` for the full human report. Read-only." },
  { name: "th_scorecard", summary: "One-glance run scorecard: tier, stage, implementation gate, coverage, slice progress, suite status, drift, revise escalations, artifact integrity, and routing summary (structured payload). COMPACT by default — the text block is a headline (full scorecard in structuredContent); pass `verbose:true` for the full human table. Read-only." },
  { name: "th_slices_sync", summary: "Upsert implementation-plan slices into state.slices (existing ids keep their status; new ids start pending). planFile overrides the plan path; dryRun computes without writing; removeMissing drops state slices no longer in the plan. Serialized under the state lock." },
  { name: "th_slice_set_status", summary: "Set a slice's status (pending|in-progress|done|blocked). Errors on an unknown slice id or invalid status. Serialized under the state lock." },
  { name: "th_interview_start", summary: "Start a scored Socratic interview: create .twinharness/interview.json with the idea + resolved confidence cutoff (default 0.80). Store-only; overwrites any prior interview. `idea` is required. (Ready when confidence ≥ cutoff.)" },
  { name: "th_interview_record", summary: "Append one agent-supplied round to the interview store and update the latest confidence. Store-only — the agent supplies ALL judgment; the tool COMPUTES nothing but `ready = confidence >= cutoff`. `scores` is a JSON object {goal,constraints,criteria}; `entities` is a JSON array of strings (both parsed in-handler). `question`, `answer`, `scores`, and `confidence` are required." },
  { name: "th_interview_status", summary: "Report the interview gate state: { started, rounds, confidence, cutoff, ready }. Ready when confidence ≥ cutoff. A missing/corrupt store reports started:false, ready:false. Read-only; COMPUTES only `ready`." },
  { name: "th_init", summary: "Initialize TwinHarness scaffolding (docs/, state.json, drift-log.md). IDEMPOTENT and non-destructive: on an already-initialized project it returns { already_initialized: true, … } WITHOUT clobbering state.json. `brownfield` records project_mode:brownfield on a fresh init. There is NO force over MCP — destructive re-init is CLI/human-only." },
  { name: "th_budget_check", summary: "Deterministic context-budget estimate (Track A-2): from agent-supplied proxy counts (filesRead, slicesBuilt, toolCalls, artifacts) compute { estTokens, pct, verdict } against the budget. The budget is `max`×1000 when given, else the persisted state.max_tokens, else the tier-aware default. verdict = ok | warn (pct≥0.75) | over (pct≥1.0). Read-only; the math is mechanical, the counts are the caller's." },
  { name: "th_handoff_write", summary: "Assemble .twinharness/HANDOFF.md (Track A-2): the run state (current_stage, slices), the `th next` recommended action, the approved-artifact Summary blocks (reuses th context pack), the open questions, an explicit 'do not re-read docs/, trust the summaries' directive, and a machine-readable resume snapshot consumed by `th handoff verify`. Use on a Fresh-session handoff when the budget verdict is 'over'. Writes one file under the state dir." },
  { name: "th_template_get", summary: "Resolve a TwinHarness template by bare name (e.g. `task-file` or `task-file.md`) and return its absolute path, content, and source layer. Precedence (no probing): a project override at `.twinharness/templates/<name>` (source `project-override`) wins over the plugin-bundled `templates/<name>` (source `plugin-bundled`); a miss returns the structured `template_not_found` with the paths searched. A traversal/absolute name is refused. Read-only." },
  { name: "th_template_list", summary: "List every resolvable template across both layers (project `.twinharness/templates/` overrides + plugin-bundled `templates/`), deduped with the resolver's precedence and marking any project override that shadows a same-named bundled template. Read-only." },
  { name: "th_repo_search", summary: "Search the GOVERNED repo (the file set the persisted repo-map covers) for a pattern, returning path:line citations under a cap — each backed by a SHA-256 read receipt (in data.receipts). Kinds: literal (substring) | regex | symbol (parsed export names) | req (REQ-ID anchors) | artifact (registered approved-artifact paths) | template (resolvable template names). Read-only; never executes content. Run th_repo_map first to build the search scope." },
  { name: "th_context_read", summary: "Batch-read a set of files under ONE shared token budget, with deterministic truncation and a per-file {file, hash, tokensConsumed} read receipt (in data.receipts). Files are read in order; while budget remains a file is included whole, the file that would overflow is truncated to a deterministic line-prefix, and any file after the budget is exhausted is reported omitted. A missing/escaping file is skipped (not fatal). Read-only." },
  { name: "th_artifact_section", summary: "Extract the BODY of a named heading from a markdown artifact under an optional token budget, with a content-hash read receipt (in data.receipts). The section is the first heading whose text equals `section` (case-insensitive); its body runs to the next same-or-higher-level heading. With maxTokens set, the body is truncated to fit by keeping a deterministic line-prefix (truncated:true). The receipt always hashes the FULL section body. Read-only." },
  { name: "th_research_write", summary: "Persist a research artifact's markdown at the HANDLER-PINNED path docs/00-research/<topic>.md (the topic is sanitized to a flat slug; slashes, `..`, and absolute/drive paths are refused) and auto-register it (first write ⇒ v1). If the topic is ALREADY a registered approved artifact, the write is REFUSED unless an explicit `version` GREATER than the registered one is supplied — a governed writer never silently clobbers or downgrades an approved doc. Returns a {file, hash} receipt. Serialized under the state lock via the register step." },
  { name: "th_sim_add", summary: "Append a simulation-ledger entry (.twinharness/simulation-ledger.json). `classification` is required (Real|Sandbox|Emulated|Mocked|Stubbed|Hardcoded). A user-visible SIMULATED entry (Mocked/Stubbed/Hardcoded/Emulated) BLOCKS the production-reality gate until retired. Optional replaces/introSlice/retireSlice/owner/userVisible mirror the CLI flags. Append-only; mints SIM-NNN." },
  { name: "th_sim_list", summary: "List simulation-ledger entries plus the ids that BLOCK the production-reality gate (non-retired, user-visible, simulated). Read-only." },
  { name: "th_sim_retire", summary: "Mark a simulation entry retired by id (status transition active→retired; entries are never deleted). A user-visible simulation REQUIRES `target` — a repo-relative source path that resolves in source — and records a BSC-4 terminal-transition receipt; an ungrounded retirement does NOT exonerate the entry (it still blocks the production-reality gate and the dist-scan join). Optional retireSlice records who/what replaced it with reality. Errors on an unknown id, a double-retire, or (user-visible) a missing/unresolving target. Serialized under the state lock." },
  { name: "th_sim_scan", summary: "Two-tier scan of dist/ for simulation patterns (mock|fake|stub|fixture|placeholder|demo|TODO|canned|hardcoded): enumerate + streaming-hash EVERY dist/ path, deep-inspect within a layered budget (per-file/aggregate/watchdog), and report both unledgered dist/ hits AND `unobserved` dist/ files the scan could not deep-inspect (file_limit|aggregate_limit|watchdog|read_error) — the coverage gaps the production-reality GATE blocks on (scan_coverage_incomplete). Advisory (exit 0; the gate refuses, not scan); records an incomplete-scan receipt under the state lock when coverage is incomplete. tests/ hits stay advisory." },
  { name: "th_gate_production_reality", summary: "Reader: report the production-reality gate (checkProductionReality). SIX conditions, each a stable error token: simulation_unretired (a non-retired user-visible simulation), production_verify_not_green, tester_record_missing, unledgered_simulation_in_dist, scan_coverage_incomplete (a dist/ file the two-tier scan could not deep-inspect, not exonerated by a signed exception), human_approval_unverified (an engaged-and-not-future humanGate stage lacks a valid snapshot+artifact-bound human approval). The SAME predicate canAdvanceStage/canUnlockImplementation/checkFinalVerification compose, so a blocked th_stage_advance/th_implementation_unlock returns the IDENTICAL token. Read-only." },
  { name: "th_inspector_write", summary: "Codebase-Inspector governed write (brownfield): write `content` to docs/00-existing-codebase-analysis.md and auto-register it as an approved artifact. The target path is FIXED in the handler — an optional `file` must equal that path exactly or the write is refused (inspector_path_pinned). `version` defaults to 1. Returns a `receipts: [{file, hash}]` payload." },
  { name: "th_tester_record", summary: "Attach the live-QA Tester run record (.twinharness/tester-record.json) that satisfies the production-reality gate's 3rd condition (tester_record_missing). `driver` is required (e.g. playwright|curl|cli-e2e). F8: pass `passed:true` to record a PASSING live run — the gate's STRICT predicate requires it (a record without `passed` is written but does NOT clear the rung). Optional provider (real|sandbox) and evidenceRef (path/URL to raw output) bind the execution receipt; the record is also bound to the repo snapshot (gitHead/dirtyTreeDigest) so a copied/stale record is rejected. Stamps ranAt. Returns a {file, hash} receipt. Mechanical: it records the verdict the live Tester supplies; it does not re-run or re-judge." },
  { name: "th_driver_record", summary: "Axis-B/BSC-3: mint the IN-PROCESS driver-dimension receipt the production-reality verification-driver rung reads (<stateDir>/driver-receipts.jsonl, hash-chained, under the state lock). Records which seed dimensions (tests-executed, typecheck, build) `verify-report.json` actually OBSERVED. SENSOR + refuse-at-creation: optional `dimension` (comma-separated) is INTERSECTED with the observed set — a claimed dimension the report does not evidence is refused (driver_dimension_unobserved), and a missing/unresolving report is refused (driver_evidence_unresolved). Omit `dimension` to record every observed seed dimension. ATTRIBUTION-ONLY (zero trust weight): the agent can mint it, so its trust label is `valid` NEVER `valid-grounded` — independent grounding is the slice-4b external Ed25519-signed producer. Returns a {file, hash} receipt." },
  { name: "th_approve", summary: "Axis-B/BSC-7: mint the IN-PROCESS human-approval receipt the humanGate precondition reads (<stateDir>/approval-receipts.jsonl, hash-chained, under the state lock). `stage` defaults to the run's current stage; it MUST be a humanGate stage (requirements, scope, architecture, ux-design, ui-design, contracts, security, final-verification) and its governing `produces` artifact MUST resolve in source — else refused at creation. The approval is bound to {stage, snapshot_coord, governing_artifact_digest}. ATTRIBUTION-ONLY (zero trust weight): the agent can mint it, so its validated status is `valid` NEVER `valid-grounded` — independent grounding is the slice-3b external Ed25519-signed producer. Returns a {file, hash} receipt." },
  { name: "th_realize", summary: "Axis-B/BSC-1: mint the IN-PROCESS realization receipt the production-reality realization rung reads (<stateDir>/realization-receipts.jsonl, hash-chained, under the state lock). Binds `req_id` to a content digest of `artifact` (the source file the REQ-ID is realized in). The gate BLOCKS a `done` slice whose owned REQ-ID has no valid, reachable, digest-fresh referent. SEPARABILITY: this does NOT set slice status — the done-claim (SliceState.status===\"done\") and this referent stay separately authored (co-authoring would be self-grounding). Refuse-at-creation: `artifact` MUST resolve in source (realization_referent_unresolved). ATTRIBUTION-ONLY (zero trust weight): the agent can mint it, so its trust label is `valid` NEVER `valid-grounded` — independent (signature-provenance) grounding is the external Ed25519-signed producer. Returns a {file, hash} receipt." },
  { name: "th_assertion_presence_record", summary: "Axis-B/BSC-2 (2a): mint the IN-PROCESS assertion-PRESENCE receipt the production-reality assertion rung reads (<stateDir>/assertion-presence-receipts.jsonl, hash-chained, under the state lock). Records, per REQ-ID, whether the recognized test files anchoring it carry a NON-TRIVIAL assertion that can fail (an empty `it()`, a smoke-only test, or a tautology like `expect(true).toBe(true)` is assertion-free). MEASURES PRESENCE / non-triviality, NOT efficacy — it does NOT prove the suite catches regressions. ATTRIBUTION-ONLY (zero trust weight): the agent can mint it, so its in-process status is `valid` NEVER `valid-grounded` — the only efficacy/independence grade is the EXTERNAL Ed25519-signed mutation-kill receipt (2b). Returns a {file, hash} receipt." },
];
